spring:
  application:
    name: git-crawler-backend

server:
  servlet:
    context-path: "/git-crawler"

management:
  endpoints:
    web:
      exposure:
        include: "*"

git-crawler:
  external:
    git-hub:
      authorization: ${GIT_HUB_AUTHORIZATION:}
  api:
    rest:
      api-public:
        path: "/api/public/rest"
      api-private:
        path: "/api/private/rest"